version: '2'

services:
  elasticsearch_master:
    build: elasticsearch/
    command: "elasticsearch -Ecluster.name=rzethon_analytics -Enode.master=true -Enode.data=false"
    hostname: elasticsearch
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk

  elasticsearch_data_1:
    build: elasticsearch/
    command: elasticsearch -Ecluster.name=rzethon_analytics -Ediscovery.zen.ping.unicast.hosts=elasticsearch
    hostname: elasticsearch_data_1
    container_name: elasticsearch_data_1
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    links:
      - elasticsearch_master
    volumes:
      - ./elasticsearch/data/1/:/usr/share/elasticsearch/data
    networks:
      - docker_elk

  elasticsearch_data_2:
    build: elasticsearch/
    command: elasticsearch -Ecluster.name=rzethon_analytics -Ediscovery.zen.ping.unicast.hosts=elasticsearch
    hostname: elasticsearch_data_2
    container_name: elasticsearch_data_2
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    links:
      - elasticsearch_master
    volumes:
      - ./elasticsearch/data/2/:/usr/share/elasticsearch/data
    networks:
      - docker_elk

  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    hostname: logstash
    container_name: logstash
    links:
      - elasticsearch_master
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      - docker_elk

  kibana:
    build: kibana/
    hostname: kibana
    container_name: kibana
    links:
      - elasticsearch_master
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - docker_elk

networks:
  docker_elk:
    driver: bridge
